---
- name: title
  type: text
  label: Title
- name: date
  type: ''
  label: Date
  hidden: true
- name: description
  type: ''
  label: Description
  description: This text will show up at the top of the page in larger font
- name: permalink
  type: text
  label: Permalink
  hidden: true
- name: layout
  type: text
  label: Layout
  default: default
  hidden: true
