---
new_page_extension: md
auto_deploy: true
admin_path: "/admin/"
webhook_url: 
collections: 
upload_dir: images
public_path: "/barnyard-organics/images"
front_matter_path: "/images"
use_front_matter_path: true
file_template: ":filename:"
