---
new_page_extension: md
auto_deploy: false
admin_path: "/admin/"
webhook_url: 
sections:
- type: jekyll-pages
  label: Pages
  create: all
- type: directory
  path: _feed-products
  label: Feed-products
  create: all
  match: "**/*"
  templates:
  - feed-product
- type: document
  path: _data/footer.yml
  label: Address, Social, etc
- type: directory
  path: _data
  label: Order Form
  create: none
  match: "**/*.{json,yaml,yml}"
  exclude: "{menus.yml,_data.footer.yml}"
upload_dir: images
public_path: "/barnyard-organics/images"
front_matter_path: "/images"
use_front_matter_path: true
file_template: ":filename:"
instant_preview: true
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site --incremental
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
