---
generator: jekyll
version: ''
upload_path: "/images/"
frontmatter_file_url_template: "/images/"
body_file_url_template: "/barnyard-organics/images/"
new_page_extension: md
auto_deploy: true
admin_path: "/admin/"
webhook_url: 
